# Generated by Django 6.0.3 on 2026-04-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_salaryrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterUniqueTogether(
            name='salaryrecord',
            unique_together={('employee', 'month', 'year')},
        ),
    ]
