# Generated by Django 6.0.3 on 2026-04-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_attendance_check_in_attendance_check_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='late_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
