# Generated by Django 6.0.3 on 2026-04-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_leave_applied_on_alter_leave_leave_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='casual_leaves',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='employee',
            name='earned_leaves',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='late_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='sick_leaves',
            field=models.IntegerField(default=8),
        ),
    ]
