# Generated by Django 6.0.3 on 2026-04-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employee_casual_leaves_employee_earned_leaves_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='late_minutes',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='applied_on',
        ),
        migrations.AlterField(
            model_name='employee',
            name='earned_leaves',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(default='Employee', max_length=50),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Sick', 'Sick'), ('Annual', 'Annual'), ('Earned', 'Earned')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
