# Generated by Django 6.0.3 on 2026-04-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_remove_employee_late_minutes_remove_leave_applied_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
