# Generated by Django 6.0.3 on 2026-04-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_employee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='rfid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
