# Generated by Django 6.0.3 on 2026-04-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_employee_name_employee_rfid'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('rfid', 'RFID')], default='web', max_length=10),
        ),
    ]
