# Generated by Django 6.0.3 on 2026-04-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_attendance_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
