# Generated by Django 6.0.3 on 2026-04-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_attendance_latitude_attendance_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='faces/'),
        ),
    ]
