# Generated by Django 6.0.3 on 2026-04-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_employee_face_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='map_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
