# Generated by Django 6.0.3 on 2026-04-20 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_employee_designation_employee_reporting_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='reporting_to',
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='employees.employee'),
        ),
    ]
