# Generated by Django 6.0.3 on 2026-04-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_remove_employee_reporting_to_employee_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='earned_leaves',
            new_name='earned_total',
        ),
        migrations.AddField(
            model_name='employee',
            name='casual_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='earned_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='sick_used',
            field=models.IntegerField(default=0),
        ),
    ]
