# Generated by Django 6.0.3 on 2026-04-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_rename_earned_leaves_employee_earned_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='casual_leaves',
            new_name='casual_total',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='sick_leaves',
            new_name='sick_total',
        ),
    ]
