# Generated by Django 4.1 on 2026-04-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0024_alter_attendance_id_alter_employee_id_alter_leave_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='mode',
            field=models.CharField(choices=[('office', 'Office'), ('remote', 'Remote')], default='office', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Remote', 'Remote')], default='Present', max_length=20),
        ),
    ]
