# Generated by Django 4.1 on 2026-04-21 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_attendance_mode_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='shift_end',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
